apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      RestartPolicy: Always
      containers:
        - name: influxdb
          image: influxdb
          imagePullPolicy: Never
          ports:
          - containerPort: 8086
            name: influxdb
            volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
  - port: 8086
    name: influxdb
    protocol: TCP
    targetPort: 8086
